apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey
helmCharts:
  - name: valkey-operator
    repo: oci://ghcr.io/hyperspike/
    version: v0.0.61-chart
    namespace: valkey
    releaseName: valkey
    includeCRDs: true
